name: "smoke test"
on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run python script
        run: python ./runctvv/test_example/smoke.py
