name: "smoke test"
on:
  pull_request:
    paths:
      - test-example/**
      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      - run: 
          smoke.py
