name: "Unit & Smoke Test"
on:
  pull_request:
    paths:
      - test-example/**
      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run python script
        run: |
          pip install -r requirements.txt
          python smoke.py
